### ISSUE TITLE
dump() category list

### ISSUE THREAD

**Issue by mberizzo** [tiipiik/oc-catalog#19]
When i attach the categories component in my page, a dump message appears:

https://github.com/tiipiik/oc-catalog/blob/4caa680f9407abb74efb1a4ed65f0dbd3cff1aec/components/Categories.php#L118

**Comment by tiipiik** [comment]
You can remove it from the default view, as it will be remove into the next release.

But you should preferably make an overriding of the view so you can make your own design (or use the same as the default), and you will not risk to have your design modified on a next release.
Tell me if you need help to make an overriding view.

**Comment by mberizzo** [comment]
Thanks @tiipiik... if you override the view, the message not disapear (you have to override the loadCategories() method, i dont know if that is possible)... I already delete the line 118 to next release.

**Comment by tiipiik** [comment]
Oh your right, sorry !
I didn't noticed the dump was inside the PHP code, not the partials.

I also removed the dump so in next release you not see that comming back.

By the way, overriding view for some plugins (like this one), is a good practice because you will avoid every breaking change in your design through releases.
